### ISSUE TITLE
Test failure: run without parameters (null)

### ISSUE THREAD

**Issue by stuartlangridge** [binarykitchen/avconv#6]
$ npm test
    > avconv@3.0.1 test /x/avconv
    > nodeunit tests/basics.js
    basics.js
    ✔ TC 1: stability tests - loading avconv function (require)
    ✖ TC 1: stability tests - run without parameters (null) 1
    Error: Expected 4 assertions, 0 ran
        at Object.test.done (/x/avconv/node_modules/nodeunit/lib/types.js:121:25)
        at Object.exports.runTest (/x/avconv/node_modules/nodeunit/lib/core.js:73:14)
        at /x/avconv/node_modules/nodeunit/lib/core.js:118:25
        at /x/avconv/node_modules/nodeunit/deps/async.js:513:13
        at iterate (/x/avconv/node_modules/nodeunit/deps/async.js:123:13)
        at /x/avconv/node_modules/nodeunit/deps/async.js:134:25
        at /x/avconv/node_modules/nodeunit/deps/async.js:515:17
        at Immediate._onImmediate (/x/avconv/node_modules/nodeunit/lib/types.js:146:17)
        at processImmediate [as _immediateCallback] (timers.js:383:17)
    TypeError: Incorrect value of args option
        at normalizeSpawnArguments (child_process.js:312:11)
        at exports.spawn (child_process.js:361:38)
        at avconv (/x/avconv/avconv.js:146:18)
        at Object.module.exports.testCase.TC 1: stability tests.testCase.run without parameters (null) 1 (/x/avconv/tests/basics.js:42:26)
        at Object.<anonymous> (/x/avconv/node_modules/nodeunit/lib/core.js:236:16)
        at Object.<anonymous> (/x/avconv/node_modules/nodeunit/lib/core.js:236:16)
        at /x/avconv/node_modules/nodeunit/lib/core.js:236:16
        at Object.exports.runTest (/x/avconv/node_modules/nodeunit/lib/core.js:70:9)
        at /x/avconv/node_modules/nodeunit/lib/core.js:118:25
        at /x/avconv/node_modules/nodeunit/deps/async.js:513:13
    ✔ TC 1: stability tests - run with empty array ([])
    ✔ TC 1: stability tests - run with invalid array parameters ([fdsfdsfsdf])
    ✔ TC 2: real tests - loading help (--help)
    ✔ TC 2: real tests - test the AvStream class
    ✔ TC 3: do a conversion - convert pokemon flv to webm
    ✔ TC 3: do a conversion - convert and kill in the middle
    ✔ TC 3: do a conversion - stream input and output
    FAILURES: 2/60 assertions failed (4308ms)
    npm ERR! Test failed.  See above for more details.
    $ node -v
    v5.7.0

**Comment by binarykitchen** [comment]
thx for reporting - just fixed that and npm-published the patch in the next version
